### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by bennyn** [wireapp/cryptobox#3]
It would be nice to have build instructions for this project. Even if it's just `cargo build`. 😃 

Because for me on Windows it fails to build:

``` bash
D:\dev\projects\wireapp\cryptobox>cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/wireapp/proteus`
    Updating git repository `https://github.com/wireapp/hkdf`
 Downloading cbor-codec v0.5.0
 Downloading byteorder v0.5.3
 Downloading libc v0.2.17
 Downloading sodiumoxide v0.0.12
 Downloading libsodium-sys v0.0.12
 Downloading pkg-config v0.3.8
   Compiling pkg-config v0.3.8
   Compiling byteorder v0.5.3
   Compiling libc v0.2.17
   Compiling cbor-codec v0.5.0
   Compiling libsodium-sys v0.0.12
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libsodium-sys v0.0.12`
process didn't exit successfully: `D:\dev\projects\wireapp\cryptobox\target\debug\build\libsodium-sys-c0d2938757495f6f\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: Das System kann die angegebene Datei nicht finden. (os error 2)"', ../src/libcore\result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by inta** [comment]
Somewhat late but as I just did those steps and found this issue on my search for the cryptobox docs:

You need to install libsodium on the system you are trying to compile cryptobox. On Linux you just need to install the libsodium and libsodium-dev packages, for Windows you may find an answer [in the docs](https://download.libsodium.org/doc/installation/).

As [proteus](https://github.com/wireapp/proteus) (dependency of cryptobox) requires sodiumoxide with default features false, you also need to use Rust nightly for your project.

**Comment by raphaelrobert** [comment]
Since we bumped this to `sodiumoxide` 0.2.x that pulls in `libsodium` automatically, `cargo build` is all you need.
